//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_TestData
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Required")]
        public string Type { get; set; }
        public string Content { get; set; }
        public string H1 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }

        [Required(ErrorMessage = "Required")]
        public string URL { get; set; }
    }
}
